
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: dashboard-data-visualization_development
test:
  <<: *default
  database: dashboard-data-visualization_test
production:
  <<: *default
  database: dashboard-data-visualization_production
  username: #Set these when you deploy
  password: